package com.edu.talim.entity.enums;

public enum Role {
    SUPER_ADMIN,
    RAHBARIYAT,
    KURSANT,
    TINGLOVCHI,
    KAFEDRA_BOSHLIGHI,
    OQUVCHI,
    SHAXSIY_XAVFSIZLIK,
    OQUV_BOLIMI_BOSHLIGHI,
    NAVBATCHILIK_QISMI,
    TALIM_SIFATI_NAZORAT,
    FAKULTET_BOSHLIGHI,
    MAGISTRATURA_BOSHLIGHI_ORINBOSARI,
    BATALYON,
    INSON_RESURSLARI,
    MAGISTRATURA_BOSHLIGHI,
    FAKULTET_BOSHLIGHI_ORINBOSARI,
    TIBBIY_XIZMAT
}